### ISSUE TITLE
Edda not displaying anything

### ISSUE THREAD

**Issue by Madhu94** [mongodb-labs/edda#137]
I'm running a mongod replica set(1 primary,1 secondary,1 arbiter) and having them log to files log2.log,log3.log,log4.log. Then I run python edda/run_edda.py log2.log log3.log log4.log. All I'm able to see is the name of my replica set. 
![image](https://cloud.githubusercontent.com/assets/9015820/14251076/d87c07b4-fa9e-11e5-9176-e6034013ed9f.png)
What am I doing wrong?

**Comment by samantharitter** [comment]
Hi @Madhu94, what version of mongod are your logs from?  Edda isn't under active maintenance, it's possible that we've fallen behind the current release.

**Comment by Madhu94** [comment]
I'm using MongoDB 3.2. But I'm really sorry, I got it. I had to move the time scroll bar under the window.

**Comment by samantharitter** [comment]
Glad to hear it!  Feel free to open another ticket if you run into any other issues.

**Comment by Madhu94** [comment]
Does edda allow for real-time updates? I shut down my primary and restarted it(now it became the secondary), but the updates are not shown.

**Comment by samantharitter** [comment]
No, in order for the updates to show up, you'd have to re-feed the logs (with the restart) through edda.

**Comment by Madhu94** [comment]
I see. Thanks a lot!.
